from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

from parity.models import EvalCase, ProbeCase, normalize_input
from parity.models.eval_case import ConversationMessage
from parity.models.eval_case import flatten_expected_output

CONVERSATIONAL_PROMPT_TEMPLATE = """[
{% for message in messages %}
{
  "role": "{{ message.role }}",
  "content": {{ message.content | dump }}
}{% if not loop.last %},{% endif %}
{% endfor %}
]"""


def promptfoo_assertion_type(expected_behavior_type: str) -> str:
    mapping = {
        "exact_output": "equals",
        "contains": "contains",
        "not_contains": "not-contains",
        "llm_rubric": "llm-rubric",
        "format_check": "javascript",
    }
    return mapping.get(expected_behavior_type, expected_behavior_type.replace("_", "-"))


def _serialize_probe_input(value: Any) -> Any:
    if isinstance(value, list):
        return [item.model_dump() if isinstance(item, ConversationMessage) else item for item in value]
    return value


def probe_to_promptfoo_test(probe: ProbeCase) -> dict[str, Any]:
    vars_payload: dict[str, Any]
    if probe.input_format == "conversation":
        vars_payload = {"messages": _serialize_probe_input(probe.input)}
    elif probe.input_format == "dict":
        vars_payload = dict(_serialize_probe_input(probe.input))
    else:
        vars_payload = {"query": probe.input}

    return {
        "description": f"[{probe.probe_type}] {probe.probe_id} — {probe.expected_behavior}",
        "vars": vars_payload,
        "assert": [
            {
                "type": promptfoo_assertion_type(probe.expected_behavior_type),
                "value": probe.rubric or probe.expected_behavior,
            }
        ],
    }


class PromptfooReader:
    def fetch_examples(self, config_path: str | Path) -> list[EvalCase]:
        path = Path(config_path)
        payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        tests = payload.get("tests", [])
        dataset_name = path.stem
        examples: list[EvalCase] = []
        for index, test in enumerate(tests):
            vars_payload = test.get("vars", {})
            input_raw = vars_payload.get("messages") or vars_payload.get("query") or vars_payload
            assertions = test.get("assert", [])
            first_assertion = assertions[0] if assertions else {}
            examples.append(
                EvalCase.model_validate(
                    {
                        "id": test.get("id", f"{dataset_name}:{index}"),
                        "source_platform": "promptfoo",
                        "source_dataset_id": str(path),
                        "source_dataset_name": dataset_name,
                        "input_raw": input_raw,
                        "input_normalized": normalize_input(input_raw),
                        "expected_output": flatten_expected_output(first_assertion.get("value")),
                        "rubric": first_assertion.get("value") if first_assertion.get("type") == "llm-rubric" else None,
                        "assertion_type": first_assertion.get("type"),
                        "metadata": {"description": test.get("description")},
                        "tags": [],
                    }
                )
            )
        return examples


class PromptfooWriter:
    def write_tests(
        self,
        probes: list[ProbeCase],
        *,
        test_file: str | Path,
        artifact_path: str | None = None,
        pr_number: int | None = None,
        version: str = "0.1.0",
        commit_sha: str = "",
    ) -> dict[str, Path]:
        path = Path(test_file)
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists():
            payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        else:
            payload = {}

        tests = payload.get("tests", [])
        tests.extend([probe_to_promptfoo_test(probe) for probe in probes])
        payload["description"] = (
            f"Parity probes for {artifact_path or 'artifacts'}"
            + (f" (PR #{pr_number})" if pr_number is not None else "")
        )
        payload["tests"] = tests
        header = f"# Generated by parity v{version} — commit {commit_sha}\n"
        path.write_text(header + yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")

        outputs = {"test_file": path}
        if any(probe.input_format == "conversation" for probe in probes):
            prompt_dir = path.parent / "prompts"
            prompt_dir.mkdir(parents=True, exist_ok=True)
            prompt_path = prompt_dir / "conversational_probe_prompt.json"
            prompt_path.write_text(CONVERSATIONAL_PROMPT_TEMPLATE, encoding="utf-8")
            outputs["prompt_file"] = prompt_path
        return outputs
